name: djv
version: '1.1'
summary: Movie playback software for use in film, VFX, and computer animation.
description: |
  DJV Imaging provides open source movie playback software for use in film, VFX and
  computer animation. Key features include -
  * Real-time playback of image sequences and movies
  * Support for industry standard file formats including Cineon, DPX, OpenEXR, and QuickTime
  * Command line utilities for batch processing
  * Cross platform support for Linux, Apple OS X, and Microsoft Windows.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures: [amd64]

icon: etc/images/djv_view_48x48.png

apps:
  djv-view:
    command: desktop-launch djv_view
    plugs: [wayland, unity7, opengl, home, removable-media, network, network-observe, optical-drive]

  djv-convert:
    command: djv_convert
    plugs: [home, removable-media, network, network-observe, optical-drive]

  djv-info:
    command: djv_info
    plugs: [home, removable-media, network, network-observe, optical-drive]
  
  djv-ls:
    command: djv_ls
    plugs: [home, removable-media, network, network-observe, optical-drive]
    
parts:
  cmake-build:
    source: https://github.com/mattiaswerner/djv.git
    source-type: git
    plugin: cmake
    after: [desktop-qt5]
    prepare: |
      sed -i 's|set(djvPackageThirdParty true)||' ../src/CMakeLists.txt
    build-packages:
      - g++
      - libgl1-mesa-dev
      - libglew-dev
      - libavdevice-dev
      - libavcodec-dev
      - libavformat-dev
      - libavfilter-dev
      - libswscale-dev
      - libavutil-dev
      - libavresample-dev
      - libilmbase-dev
      - libjpeg-dev
      - libpng-dev
      - qtbase5-dev
      - libqt5svg5-dev
      - libqt5opengl5-dev
      - qttools5-dev-tools
      - libtiff5-dev
      - zlib1g-dev

    stage-packages:
      - libqt5gui5
      - libstdc++6
      - zlib1g
      - libpcre3
      - liblzma5
